# name: mm35626-collector
services:
  mongo:
    extends:
      file: common-services.yml
      service: mongo
    ports:
      - "127.0.0.1:20600:27017"
    volumes:
      - mm35626_mongo_volume:/data/db
    restart: unless-stopped
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    ports:
      - "127.0.0.1:8191:8191"
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped
  dirtyjson:
    image: martinomensio/dirtyjson
    ports:
      - "127.0.0.1:12345:12345"
    restart: unless-stopped
  claimreview-collector-full:
    extends:
      file: common-services.yml
      service: claimreview-collector
    depends_on:
      - mongo
      - flaresolverr
      - dirtyjson
    image: martinomensio/claimreview-collector:${CLAIMREVIEW_COLLECTOR_TAG:-latest}
    ports:
      - "127.0.0.1:20500:8000"
    environment:
      - ROLE=full
      - PUBLISH_GITHUB=true
      - DIRTYJSON_REST_ENDPOINT=http://dirtyjson:12345
      - TWITTER_CONNECTOR=https://misinfo.me/misinfo/api/twitter
      - MISINFO_BACKEND=https://misinfo.me
      - FLARESOLVERR_HOST=flaresolverr:8191
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GOOGLE_FACTCHECK_EXPLORER_COOKIE=${GOOGLE_FACTCHECK_EXPLORER_COOKIE}
      - TEXTRAZOR_KEY_0=${TEXTRAZOR_KEY_0}
      - TEXTRAZOR_KEY_1=${TEXTRAZOR_KEY_1}
      - TEXTRAZOR_KEY_2=${TEXTRAZOR_KEY_2}
      - TEXTRAZOR_KEY_3=${TEXTRAZOR_KEY_3}
      - TEXTRAZOR_KEY_4=${TEXTRAZOR_KEY_4}
      - TEXTRAZOR_KEY_5=${TEXTRAZOR_KEY_5}
      - TEXTRAZOR_KEY_6=${TEXTRAZOR_KEY_6}
      - TEXTRAZOR_KEY_7=${TEXTRAZOR_KEY_7}
      - TEXTRAZOR_KEY_8=${TEXTRAZOR_KEY_8}
      - TEXTRAZOR_KEY_9=${TEXTRAZOR_KEY_9}
      - TEXTRAZOR_KEY_10=${TEXTRAZOR_KEY_10}
      - TEXTRAZOR_KEY_11=${TEXTRAZOR_KEY_11}
      - TEXTRAZOR_KEY_12=${TEXTRAZOR_KEY_12}
      - TEXTRAZOR_KEY_13=${TEXTRAZOR_KEY_13}
      - TEXTRAZOR_KEY_14=${TEXTRAZOR_KEY_14}
      - TEXTRAZOR_KEY_15=${TEXTRAZOR_KEY_15}
      - TEXTRAZOR_KEY_16=${TEXTRAZOR_KEY_16}
      - TEXTRAZOR_KEY_17=${TEXTRAZOR_KEY_17}
      - TEXTRAZOR_KEY_18=${TEXTRAZOR_KEY_18}
      - TEXTRAZOR_KEY_19=${TEXTRAZOR_KEY_19}
      - TEXTRAZOR_KEY_20=${TEXTRAZOR_KEY_20}
      - TEXTRAZOR_KEY_21=${TEXTRAZOR_KEY_21}
      - TEXTRAZOR_KEY_22=${TEXTRAZOR_KEY_22}
      - TEXTRAZOR_KEY_23=${TEXTRAZOR_KEY_23}
      - TEXTRAZOR_KEY_24=${TEXTRAZOR_KEY_24}
      - TEXTRAZOR_KEY_25=${TEXTRAZOR_KEY_25}
      - TEXTRAZOR_KEY_26=${TEXTRAZOR_KEY_26}
      - TEXTRAZOR_KEY_27=${TEXTRAZOR_KEY_27}
      - TEXTRAZOR_KEY_28=${TEXTRAZOR_KEY_28}
      - TEXTRAZOR_KEY_29=${TEXTRAZOR_KEY_29}
      - TEXTRAZOR_KEY_30=${TEXTRAZOR_KEY_30}
      - TEXTRAZOR_KEY_31=${TEXTRAZOR_KEY_31}
      - TEXTRAZOR_KEY_32=${TEXTRAZOR_KEY_32}
      - TEXTRAZOR_KEY_33=${TEXTRAZOR_KEY_33}
      - TEXTRAZOR_KEY_34=${TEXTRAZOR_KEY_34}
      - TEXTRAZOR_KEY_35=${TEXTRAZOR_KEY_35}
      - TEXTRAZOR_KEY_36=${TEXTRAZOR_KEY_36}
      - TEXTRAZOR_KEY_37=${TEXTRAZOR_KEY_37}
      - TEXTRAZOR_KEY_38=${TEXTRAZOR_KEY_38}
      - TEXTRAZOR_KEY_39=${TEXTRAZOR_KEY_39}
      - TEXTRAZOR_KEY_40=${TEXTRAZOR_KEY_40}
    restart: unless-stopped

volumes:
  mm35626_mongo_volume:
    external: true
