# This docker configuration is for dev environment.
# For production use the script build_frontend.sh and read README.md
version: '3.7'
services:

  # the definition of the container for the database
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017" # with the port we can connect directly even outside compose network
    volumes:
      - mongo_volume:/data/db # the volume is for making database persistent
    logging:
      driver: none
  backend:
    command: python3 server.py # override command in development to get reload after file changes
    build:
      context: backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_HOST=mongo:27017
    volumes:
      - ./backend:/app # this mapping allows change in the code without rebuilding the container

  frontend:
    build:
      context: frontend
    ports:
      - "4200:4200" # the port on the host is 4200, in the container is 4200
    volumes:
      - ./frontend:/app
      - node_modules_frontend:/app/node_modules # this folder is not shared, it will go on a separate volume

volumes:
  mongo_volume:
  node_modules_frontend:
