name: main

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: "0 7 * * 1" # monday morning, after dependabot
  pull_request:

jobs:
  concurrency:
    name: wait for other concurrent workflows
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v3
    - 
      uses: ahmadnassri/action-workflow-queue@v1
  test:
    name: Integration tests
    runs-on: ubuntu-latest
    needs: concurrency
    steps:
    - 
      uses: actions/checkout@v3
    -
      name: run tests
      run: echo "TODO"
  merge:
    permissions: write-all
    name: Merge PR
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.event.pull_request }}
    steps:
    -
      name: merge a pull request
      uses: sudo-bot/action-pull-request-merge@v1.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        number: ${{ github.event.pull_request.number }}
        allowed-usernames-regex: ^dependabot|MartinoMensio$
  docker:
    name: Docker publish tag latest
    runs-on: ubuntu-latest
    needs: test
    if: github.ref_name == 'master'
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{github.ref_name}}
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Get Releases with latest date
      id: date
      run: echo "TAG=TODO" >> $GITHUB_ENV
    -
      name: Build and push
      run: echo "TODO"